---
title: "Item Norming"
output: html_notebook
---

```{r}
library(tidyverse)

df_raw <- read.csv("data/WIW_Norming_for_preregistered_study.csv")

reverse_items <- c(
  "Earthquake",
  "Tornado",
  "Fastfood",
  "Marine",
  "Police",
  "Mugging",
  "Crushed",
  "Dysentery",
  "Drunk",
  "Football"
)

df_wide <- df_raw %>%
  filter(Status==0) %>%
  filter(Check_trial == 5) %>%
  select(-Check_trial) %>%
  mutate(sex = if_else(sex == 1, "male", "female"))

df <- df_wide %>%
  gather(trial, response, Earthquake:Rape) %>%
  mutate(response = ifelse(trial %in% reverse_items, 6-response, response))
```

As predicted, in all items the "less expected" outcome was judged to be less likely. Plot below shows mean likelihood rating by item along with approximate 95% confidence intervals.

```{r}
# standard error function
stderr <- function(x) {
          sqrt(var(x[!is.na(x)]) / length(x[!is.na(x)]))
}


df %>%
  group_by(trial) %>%
  summarize(
    Mean = mean(response),
    UL = mean(response) + 1.96*stderr(response),
    LL = mean(response) - 1.96*stderr(response)
    ) %>%
  ggplot() +
  aes(x = reorder(trial, -Mean), y = Mean, ymin = LL, ymax=UL) +
  geom_pointrange() +
  geom_hline(yintercept = 3, linetype="dashed") +
  coord_cartesian(ylim=c(1,5)) +
  theme_bw()+
  labs(x = "Trial", y="Mean Likelihoods Judgment") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

