---
title: "R Notebook"
output: html_notebook
---

```{r}

library(tidyverse)

d_raw <- read.csv("data/WIW+Judgment+Task+Preregistered_March+30%2C+2018_11.17.csv")

d_wide <- d_raw %>%
  rename(duration = Duration..in.seconds.) %>%
  select(workerId, age, sex, attn, duration, contains("_trial"), -contains("_trial_")) %>%
  filter(Check_trial == 0, attn == 1) %>%
  rename(
    Corruption_trial = corruption_trial,
    Clerk_trial = clerk_trial,
    Flattire_trial = flattire_trial,
    Rape_trial = rape_trial)

reverse_items <- c( # sadly, only 6 of 10 items were reversed! :(
  "Cancer_trial",
  "Heater_trial",
  "Flattire_trial",
  "Clerk_trial",
  "Corruption_trial",
  "Rape_trial"
)

d_tidy <- d_wide %>%
  gather(trial, response, Earthquake_trial:BigDiff5_trial) %>%
  mutate(trial_type = ifelse(grepl("[0-9]", trial), "filler", "experimental")) %>%
  mutate(trial_type = ifelse(grepl("BigDiff",trial), "filler-diff", trial_type)) %>%
  mutate(likely_2nd = ifelse((trial %in% reverse_items), 1, 0))

d <- d_tidy %>%
  filter(trial_type == "experimental", trial != "Check_trial") %>%
  mutate(response = ifelse(likely_2nd==1, (1-response), response))
```

```{r}
# normal = more likely is 1
# reverse = less likely is 1

d %>%
  group_by(trial) %>%
  summarize(mean_response = mean(response)) %>%
  ggplot(aes(x=trial, y = mean_response)) +
  geom_bar(stat="identity") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
library(brms)
fit <- brm(
  response ~ 0 + intercept + (1|workerId) + (1|trial),
  data = d,
  family = bernoulli(), # student(), #cumulative(), #bernoulli(), etc
  control = list(adapt_delta = .80),
  cores = parallel::detectCores(),
  iter = 2000)
```

```{r}
summary(fit)
```

