---
title: "R Notebook"
output: html_notebook
---

```{r}

library(tidyverse)

d_raw <- read.csv("data/WIW+Judgment+Task+Preregistered+-+Likert_April+20%2C+2018_17.08.csv")

d_wide <- d_raw %>%
  rename(duration = Duration..in.seconds.) %>%
  select(workerId, age, sex, attn, duration, contains("_trial"), -contains("_trial_")) %>%
  filter(
    Check1_trial == -1, 
    Check2_trial == -2, 
    Check3_trial == 1, 
    attn == 1,
    !is.na(workerId)
    ) %>%
  rename(
    Corruption_trial = corruption_trial,
    Clerk_trial = clerk_trial,
    Flattire_trial = flattire_trial,
    Rape_trial = rape_trial)

# normal = more likely is 1
# reverse = less likely is 1

reverse_items <- c(
  "Cancer_trial",
  "Heater_trial",
  "Flattire_trial",
  "Clerk_trial",
  "Corruption_trial",
  "Rape_trial",
  "Earthquake_trial",
  "Fastfood_trial",
  "Police_trial"
)

d_tidy <- d_wide %>%
  select(-Check1_trial, -Check2_trial, -Check3_trial) %>%
  gather(trial, response, Tornado_trial:BigDiff5_trial) %>%
  mutate(trial_type = ifelse(grepl("[0-9]", trial), "filler", "experimental")) %>%
  mutate(trial_type = ifelse(grepl("BigDiff",trial), "filler-diff", trial_type)) %>%
  mutate(likely_2nd = ifelse((trial %in% reverse_items), 1, 0))

d <- d_tidy %>%
  filter(trial_type == "experimental") %>%
  mutate(response = ifelse(likely_2nd==1, response*-1, response))
```

```{r}
# normal = more likely is 1
# reverse = less likely is 1

d %>%
  group_by(trial) %>%
  summarize(mean_response = mean(response)) %>%
  ggplot(aes(x=trial, y = mean_response)) +
  geom_bar(stat="identity") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
library(brms)

devtools::source_gist(id = "f1994c0f8325abbc5d300600744af39d", filename="cbrm.R")

fit_exp2 <- cbrm(
  response ~ trial + (1|workerId),
  data = d %>% mutate(response = response + 3),
  family = cumulative(), # student(), #cumulative(), #bernoulli(), etc
  prior = prior(normal(0,3),class="b"),
  control = list(adapt_delta = .80),
  cores = parallel::detectCores(),
  sample_prior = TRUE,
  iter = 2000,
  cached_file = "fit_exp2.rds"
  )
```

```{r}
summary(fit_exp2)

# So we get four intercepts representing the cumulative log odds of the different responses. 
# The question is whether the cumulative odds of responses 1 and 2 are greater than the cumulative log odds of responses 4 and 5. I'm getting this by comparing the `intercept[2]` 
# representing log odds of 1 and 2 against the inverse of `intercept[3]`, where `intercept[3]` itself represents the log odds of responses 1, 2, and 3 and therefore its inverse represents # the log odds of the remaining responses 4 and 5.

# test whether intercepts are different
h <- hypothesis(fit_exp2, "Intercept[2] = -Intercept[3]")

h$hypothesis$Evid.Ratio
```

```{r}
fit_exp2_re <- cbrm(
  response ~ (1|trial) + (1|workerId),
  data = d %>% mutate(response = response + 3),
  family = cumulative(), # student(), #cumulative(), #bernoulli(), etc
  # prior = prior(normal(0,3), class="Intercept"),
  control = list(adapt_delta = .80),
  cores = parallel::detectCores(),
  sample_prior = TRUE,
  iter = 2000,
  cached_file = "fit_exp2_re.rds"
  )
```

```{r}
summary(fit_exp2_re)

h2 <- hypothesis(fit_exp2_re, "Intercept[2] = -Intercept[3]")

h2$hypothesis$Evid.Ratio
```

